swagger: "2.0"
info:
  version: "2.0.0"
  title: SAMPLE API
host: localhost:4000
basePath: /v2
#
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json; charset=utf-8
securityDefinitions:
  requiresAccessToken:
    type: apiKey
    name: Cookie
    in: header

##################### NOTE: Node Swagger middleware only supports swagger 2.0 #####################
#
#  Use reference at https://swagger.io/docs/specification/2-0/basic-structure/ instead of google results
#  Current latest is OpenAPI 3.0, formerly known as Swagger 3.0
#
###################################################################################################

paths:
  /car/{id}:
    x-swagger-router-controller: Cars
    x-wireswag-model: Car
    get:
      tags:
        - cars
      description: Returns a car
      operationId: getCar
      parameters:
        - in: path
          name: id
          description: Unique identifier of a Car
          required: true
          type: string
          x-example: 1aa2313
          x-wireswag-operationId: getCarId
      produces:
        - application/json
      responses:
        200:
          headers:
            Content-Type:
              type: string
              default: application/json; charset=utf-8
          description: A car
